"""init migration

Revision ID: 2992760f3dfe
Revises: 72f7d1098e2e
Create Date: 2023-06-25 02:47:20.255531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2992760f3dfe'
down_revision = '72f7d1098e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.VARCHAR(length=40), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
