"""init migration

Revision ID: 731276e42dda
Revises: 1ee877454f67
Create Date: 2023-06-25 02:32:27.405023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731276e42dda'
down_revision = '1ee877454f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
